<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sqx</groupId>
        <artifactId>realcloudagent-1780772159829-server</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>sqx-modules</artifactId>
    <packaging>pom</packaging>
    <name>sqx-modules</name>

    <modules>
        <module>sqx-auth</module>
    </modules>
</project>
